### ISSUE TITLE
build not working

### ISSUE THREAD

**Issue by nlmaca** [jeweltheme/basix-admin#4]
im getting errors like the others. npm and yarn are not building the package. 
getting chartlist errors, error in css-loader, error bin /src/App.vue, /src/main.js

is there somewhere where i can just get a working copy?

**Comment by bidossessi** [comment]
Actually, it looks like this project has been incomplete since it was uploaded. I've tried getting the version on the website, and it has the same issues.

**Comment by litonarefin** [comment]
Hello @nlmaca and @bidossessi,
We're working on a new Design. We will upload fresh Design by next week.
Thanks

**Comment by RafikFarhad** [comment]
Hello @litonarefin  
Did you upload the fresh working copy?

**Comment by litonarefin** [comment]
Hello @RafikFarhad,
Couldn't upload because of my sickness. Will do by next week. Busy with our website dedicated on "Vue.js Admin" Template https://vuejsadmin.com.
Website will be Live on next week. Then this template will be updated also.

Including "Basix Admin" there are few more "FREE Admin Templates" coming with Fresh Design.

Thanks

**Comment by litonarefin** [comment]
Basix Admin Updated and Build Functionality Added.
